### ISSUE TITLE
docker-compose up fails with guice inject errors

### ISSUE THREAD

**Issue by yoooyle** [idsc-frazzoli/amod#108]
> jayyuan@jayy-C02WC0ADHTDG:~/code/amod$ docker-compose up
Recreating amod_aido-host_1 ... done
Recreating amod_aido-guest_1 ... done
Attaching to amod_aido-host_1, amod_aido-guest_1
aido-host_1   | StringServerSocket: accept connections
aido-host_1   | StringServerSocket: accept connections
aido-host_1   | StringServerSocket: closed
aido-host_1   | StringServerSocket: thread stop
aido-host_1   | AidoHost config: {SanFrancisco.20080518}
aido-host_1   | obtain as resource: [/scenario/SanFrancisco/20080518/scenario.zip]
aido-host_1   | Using scenario directory: /amod/target
aido-host_1   | 2019-01-04 22:27:40,100  WARN MGC:175 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
aido-host_1   | 2019-01-04 22:27:40,847  INFO Logger:? dataFileCache open start
aido-host_1   | 2019-01-04 22:27:41,344  WARN MGC:175 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
aido-host_1   | 2019-01-04 22:27:41,450  WARN MGC:175 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
aido-host_1   | 2019-01-04 22:27:41,450  WARN MGC:175 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
aido-host_1   | 2019-01-04 22:27:41,455  WARN MGC:175 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
aido-host_1   | 2019-01-04 22:27:41,492  WARN MGC:175 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
aido-host_1   | 2019-01-04 22:27:41,533  WARN MGC:175 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
aido-host_1   | 2019-01-04 22:27:41,534  WARN MGC:175 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
aido-host_1   | 2019-01-04 22:27:41,542  WARN MGC:175 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
aido-host_1   | 2019-01-04 22:27:41,552  WARN MGC:175 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
aido-host_1   | 2019-01-04 22:27:41,558  WARN MGC:175 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
aido-host_1   | 2019-01-04 22:27:41,559  WARN MGC:175 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
aido-host_1   | 2019-01-04 22:27:41,561  WARN MGC:175 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
aido-host_1   | 2019-01-04 22:27:41,567  WARN MGC:175 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
aido-host_1   | 2019-01-04 22:27:41,595  WARN MGC:175 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
aido-host_1   | 2019-01-04 22:27:41,595  WARN MGC:175 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
aido-host_1   | working in directory 
aido-host_1   | /amod/target
aido-host_1   | 2019-01-04 22:27:41,726  INFO Config:563 setting context to [file:/amod/target/]
aido-host_1   | 2019-01-04 22:27:41,817  INFO MatsimXmlParser:155 starting to parse xml from url file:/amod/target/config_full.xml ...
aido-host_1   | 2019-01-04 22:27:41,907  INFO ConfigReader:102 using config_v2-reader
aido-host_1   | 2019-01-04 22:27:41,908  INFO MatsimXmlParser:306 Using local DTD from classpath:dtd/config_v2.dtd
aido-host_1   | 2019-01-04 22:27:41,919  WARN PlanCalcScoreConfigGroup$ActivityParams:744 Setting minimalDuration different from zero is discouraged.  It is probably implemented correctly, but there is as of now no indication that it makes the results more realistic.  KN, Sep'08 This message given only once.
aido-host_1   | 2019-01-04 22:27:41,925  INFO Config:563 setting context to [file:/amod/target/config_full.xml]
aido-host_1   | 2019-01-04 22:27:41,950  INFO Config:563 setting context to [file:/amod/target/]
aido-host_1   | 2019-01-04 22:27:41,983  INFO ScenarioLoaderImpl:108 loading scenario from base directory: /amod/target/
aido-host_1   | 2019-01-04 22:27:41,983  INFO ScenarioLoaderImpl:130 loading network from file:/amod/target/network.xml.gz
aido-host_1   | 2019-01-04 22:27:41,985  INFO MatsimXmlParser:155 starting to parse xml from url file:/amod/target/network.xml.gz ...
aido-host_1   | 2019-01-04 22:27:41,995  INFO MatsimNetworkReader:95 using network_v2-reader.
aido-host_1   | 2019-01-04 22:27:41,995  INFO MatsimXmlParser:306 Using local DTD from classpath:dtd/network_v2.dtd
aido-host_1   | 2019-01-04 22:27:42,001  INFO NetworkImpl:156  node # 1
aido-host_1   | 2019-01-04 22:27:42,001  INFO NetworkImpl:156  node # 2
aido-host_1   | 2019-01-04 22:27:42,002  INFO NetworkImpl:156  node # 4
aido-host_1   | 2019-01-04 22:27:42,003  INFO NetworkImpl:156  node # 8
aido-host_1   | 2019-01-04 22:27:42,005  INFO NetworkImpl:156  node # 16
aido-host_1   | 2019-01-04 22:27:42,007  INFO NetworkImpl:156  node # 32
aido-host_1   | 2019-01-04 22:27:42,011  INFO NetworkImpl:156  node # 64
aido-host_1   | 2019-01-04 22:27:42,018  INFO NetworkImpl:156  node # 128
aido-host_1   | 2019-01-04 22:27:42,030  INFO NetworkImpl:156  node # 256
aido-host_1   | 2019-01-04 22:27:42,053  INFO NetworkImpl:156  node # 512
aido-host_1   | 2019-01-04 22:27:42,081  INFO NetworkImpl:156  node # 1024
aido-host_1   | 2019-01-04 22:27:42,103  INFO NetworkImpl:156  node # 2048
aido-host_1   | 2019-01-04 22:27:42,123  INFO NetworkImpl:156  node # 4096
aido-host_1   | 2019-01-04 22:27:42,167  INFO NetworkImpl:156  node # 8192
aido-host_1   | 2019-01-04 22:27:42,215  INFO NetworkImpl:156  node # 16384
aido-host_1   | 2019-01-04 22:27:42,257  INFO NetworkImpl:152  link # 1
aido-host_1   | 2019-01-04 22:27:42,258  INFO NetworkImpl:152  link # 2
aido-host_1   | 2019-01-04 22:27:42,259  INFO NetworkImpl:152  link # 4
aido-host_1   | 2019-01-04 22:27:42,260  INFO NetworkImpl:152  link # 8
aido-host_1   | 2019-01-04 22:27:42,261  INFO NetworkImpl:152  link # 16
aido-host_1   | 2019-01-04 22:27:42,263  INFO NetworkImpl:152  link # 32
aido-host_1   | 2019-01-04 22:27:42,266  INFO NetworkImpl:152  link # 64
aido-host_1   | 2019-01-04 22:27:42,270  INFO NetworkImpl:152  link # 128
aido-host_1   | 2019-01-04 22:27:42,277  INFO NetworkImpl:152  link # 256
aido-host_1   | 2019-01-04 22:27:42,283  INFO NetworkImpl:152  link # 512
aido-host_1   | 2019-01-04 22:27:42,291  INFO NetworkImpl:152  link # 1024
aido-host_1   | 2019-01-04 22:27:42,313  WARN LinkImpl:148 length=0.0 of link id 1150 may cause problems
aido-host_1   | 2019-01-04 22:27:42,313  WARN LinkImpl:150  Future occurences of this logging statement are suppressed.
aido-host_1   | 2019-01-04 22:27:42,313  WARN LinkImpl:108 fromNode=toNode=[id=3430831397][coord=[x=1443109.3028544427][y=429941.83570740046]][type=null][nof_inlinks=0][nof_outlinks=0]: link is a loop
aido-host_1   | 2019-01-04 22:27:42,314  WARN LinkImpl:110  Future occurences of this logging statement are suppressed.
aido-host_1   | 2019-01-04 22:27:42,314  WARN NodeImpl:87 [id=3430831397][coord=[x=1443109.3028544427][y=429941.83570740046]][type=null][nof_inlinks=0][nof_outlinks=1]: inlink_id=1150 is now in- and out-link
aido-host_1   | 2019-01-04 22:27:42,315  WARN NodeImpl:88  This message given only once.
aido-host_1   | 2019-01-04 22:27:42,321  INFO NetworkImpl:152  link # 2048
aido-host_1   | 2019-01-04 22:27:42,343  INFO NetworkImpl:152  link # 4096
aido-host_1   | 2019-01-04 22:27:42,395  INFO NetworkImpl:152  link # 8192
aido-host_1   | 2019-01-04 22:27:42,484  INFO NetworkImpl:152  link # 16384
aido-host_1   | 2019-01-04 22:27:42,647  INFO NetworkImpl:152  link # 32768
aido-host_1   | 2019-01-04 22:27:42,949  INFO ScenarioLoaderImpl:182 no facilities file set in config, therefore not loading any facilities.  This is not a problem except if you are using facilities
aido-host_1   | 2019-01-04 22:27:42,949  INFO ScenarioLoaderImpl:192 no facility-attributes file set in config, not loading any facility attributes
aido-host_1   | 2019-01-04 22:27:42,949  INFO ScenarioLoaderImpl:199 loading population from file:/amod/target/population.xml.gz
aido-host_1   | 2019-01-04 22:27:42,955  INFO MatsimXmlParser:155 starting to parse xml from url file:/amod/target/population.xml.gz ...
aido-host_1   | 2019-01-04 22:27:42,959  INFO PopulationReader:109 using population_v6-reader.
aido-host_1   | 2019-01-04 22:27:42,959  INFO MatsimXmlParser:306 Using local DTD from classpath:dtd/population_v6.dtd
aido-host_1   | 2019-01-04 22:27:42,969  INFO PopulationImpl:112  person # 1
aido-host_1   | 2019-01-04 22:27:42,970  INFO PopulationImpl:112  person # 2
aido-host_1   | 2019-01-04 22:27:42,971  INFO PopulationImpl:112  person # 4
aido-host_1   | 2019-01-04 22:27:42,972  INFO PopulationImpl:112  person # 8
aido-host_1   | 2019-01-04 22:27:42,974  INFO PopulationImpl:112  person # 16
aido-host_1   | 2019-01-04 22:27:42,976  INFO PopulationImpl:112  person # 32
aido-host_1   | 2019-01-04 22:27:42,981  INFO PopulationImpl:112  person # 64
aido-host_1   | 2019-01-04 22:27:42,989  INFO PopulationImpl:112  person # 128
aido-host_1   | 2019-01-04 22:27:43,000  INFO PopulationImpl:112  person # 256
aido-host_1   | 2019-01-04 22:27:43,015  INFO PopulationImpl:112  person # 512
aido-host_1   | 2019-01-04 22:27:43,035  INFO PopulationImpl:112  person # 1024
aido-host_1   | 2019-01-04 22:27:43,085  INFO PopulationImpl:112  person # 2048
aido-host_1   | 2019-01-04 22:27:43,135  INFO PopulationImpl:112  person # 4096
aido-host_1   | 2019-01-04 22:27:43,219  INFO PopulationImpl:112  person # 8192
aido-host_1   | 2019-01-04 22:27:43,338  INFO PopulationImpl:112  person # 16384
aido-host_1   | 2019-01-04 22:27:43,446  INFO PopulationUtils:992  person # 23475
aido-host_1   | 2019-01-04 22:27:43,447  INFO ScenarioLoaderImpl:235 no person-attributes file set in config, not loading any person attributes
aido-host_1   | 2019-01-04 22:27:43,447  INFO ScenarioLoaderImpl:247 no households file set in config, not loading households
aido-host_1   | 2019-01-04 22:27:43,447  INFO ScenarioLoaderImpl:258 no household-attributes file set in config, not loading any household attributes
aido-host_1   | 2019-01-04 22:27:43,447  INFO ScenarioLoaderImpl:284 no transit schedule file set in config, not loading any transit schedule
aido-host_1   | 2019-01-04 22:27:43,448  INFO ScenarioLoaderImpl:311 no transit vehicles file set in config, not loading any transit vehicles
aido-host_1   | 2019-01-04 22:27:43,453  INFO MatsimXmlParser:147 starting to parse xml from file /amod/target/av.xml ...
aido-host_1   | 2019-01-04 22:27:43,457  INFO MatsimXmlParser:306 Using local DTD from classpath:dtd/av_v1.dtd
aido-host_1   | 2019-01-04 22:27:43,462  WARN ReflectiveConfigGroup:227 unknown parameter dispatchPeriod for group dispatcher. Here are the valid parameter names: []
aido-host_1   | 2019-01-04 22:27:43,463  WARN ReflectiveConfigGroup:228 Only the string value will be remembered
aido-host_1   | aidoprep NumberOfVehicles=500
aido-host_1   | ++++++++++++++++++++++++ NETWORK PREPARER +++++++++++++++++++++++++++++++
aido-host_1   | Network (Link) size original: 56394
aido-host_1   | 2019-01-04 22:27:43,470  INFO NetworkWriter:68 Writing network to file: preparedNetwork.xml.gz...
aido-host_1   | 2019-01-04 22:27:44,228  INFO NetworkWriter:71 done.
aido-host_1   | Opening the gzip file.......................... : preparedNetwork.xml.gz
aido-host_1   | Transferring bytes from the compressed file to the output file........: Transfer successful
aido-host_1   | The file and stream is ......closing.......... : closed
aido-host_1   | saved converted network to: preparedNetwork.xml
aido-guest_1  | Nominal fleet size: 587
aido-guest_1  | Chosen fleet size:  20
aido-guest_1  | minimum longitude in network: -122.5324551802933
aido-guest_1  | maximum longitude in network: -122.34399574000841
aido-guest_1  | minimum latitude  in network: 37.55197020161227
aido-guest_1  | maximum latitude  in network: 37.84836063248121
aido-host_1   | 2019-01-04 22:27:44,873  INFO PopulationTools:31 All people in population  which have activities outside network are removed.
aido-host_1   | we are at person # 1. 
aido-host_1   | we are at person # 2. 
aido-host_1   | we are at person # 4. 
aido-host_1   | we are at person # 8. 
aido-host_1   | we are at person # 16. 
aido-host_1   | we are at person # 32. 
aido-host_1   | we are at person # 64. 
aido-host_1   | we are at person # 128. 
aido-host_1   | we are at person # 256. 
aido-host_1   | we are at person # 512. 
aido-host_1   | we are at person # 1024. 
aido-host_1   | we are at person # 2048. 
aido-host_1   | we are at person # 4096. 
aido-host_1   | we are at person # 8192. 
aido-host_1   | we are at person # 16384. 
aido-host_1   | population size after removing all people outside the network: 23475
aido-host_1   | 2019-01-04 22:27:44,915  INFO PopulationTools:67 All people in population  which have activities outside the time interval [0, 108000) are removed.
aido-host_1   | we are at person # 1. 
aido-host_1   | we are at person # 2. 
aido-host_1   | we are at person # 4. 
aido-host_1   | we are at person # 8. 
aido-host_1   | we are at person # 16. 
aido-host_1   | we are at person # 32. 
aido-host_1   | we are at person # 64. 
aido-host_1   | we are at person # 128. 
aido-host_1   | we are at person # 256. 
aido-host_1   | we are at person # 512. 
aido-host_1   | we are at person # 1024. 
aido-host_1   | we are at person # 2048. 
aido-host_1   | we are at person # 4096. 
aido-host_1   | we are at person # 8192. 
aido-host_1   | we are at person # 16384. 
aido-host_1   | population size after removing all people outside the time interval: 23475
aido-host_1   | 2019-01-04 22:27:45,036  INFO Counter:61 [PopulationWriter] dumped person # 1
aido-host_1   | 2019-01-04 22:27:45,036  INFO Counter:61 [PopulationWriter] dumped person # 2
aido-host_1   | 2019-01-04 22:27:45,036  INFO Counter:61 [PopulationWriter] dumped person # 4
aido-host_1   | 2019-01-04 22:27:45,037  INFO Counter:61 [PopulationWriter] dumped person # 8
aido-host_1   | 2019-01-04 22:27:45,037  INFO Counter:61 [PopulationWriter] dumped person # 16
aido-host_1   | 2019-01-04 22:27:45,038  INFO Counter:61 [PopulationWriter] dumped person # 32
aido-host_1   | 2019-01-04 22:27:45,039  INFO Counter:61 [PopulationWriter] dumped person # 64
aido-host_1   | 2019-01-04 22:27:45,041  INFO Counter:61 [PopulationWriter] dumped person # 128
aido-host_1   | 2019-01-04 22:27:45,044  INFO Counter:61 [PopulationWriter] dumped person # 256
aido-host_1   | 2019-01-04 22:27:45,049  INFO PopulationWriter:139 Population written to: preparedPopulation.xml.gz
aido-host_1   | 2019-01-04 22:27:45,050  INFO Counter:67 [PopulationWriter] dumped person # 500
aido-host_1   | Opening the gzip file.......................... : preparedPopulation.xml.gz
aido-host_1   | Transferring bytes from the compressed file to the output file........: Transfer successful
aido-host_1   | The file and stream is ......closing.......... : closed
aido-host_1   | 2019-01-04 22:27:45,055  INFO Config:563 setting context to [file:/amod/target/]
aido-host_1   | 2019-01-04 22:27:45,058  INFO Config:563 setting context to [file:/amod/target/]
aido-host_1   | changing dispatcher to AidoDispatcherHost
aido-host_1   | looking for av.xml file at /amod/target/av.xml
aido-host_1   | changing vehicle number to 20
aido-host_1   | looking for av.xml file at /amod/target/av.xml
aido-host_1   | working in directory 
aido-host_1   | /amod/target
aido-host_1   | server available...
aido-host_1   | 2019-01-04 22:27:45,138  INFO Config:563 setting context to [file:/amod/target/]
aido-host_1   | 2019-01-04 22:27:45,139  INFO MatsimXmlParser:155 starting to parse xml from url file:/amod/target/config.xml ...
aido-host_1   | 2019-01-04 22:27:45,141  INFO ConfigReader:102 using config_v2-reader
aido-host_1   | 2019-01-04 22:27:45,141  INFO MatsimXmlParser:306 Using local DTD from classpath:dtd/config_v2.dtd
aido-host_1   | 2019-01-04 22:27:45,144  INFO GlobalConfigGroup:71 setting number of threads to: 2
aido-host_1   | 2019-01-04 22:27:45,146  WARN PlanCalcScoreConfigGroup$ReflectiveDelegate:1305 Setting pathSizeLogitBeta different from zero is experimental.  KN, Sep'08
aido-host_1   | 2019-01-04 22:27:45,150  INFO PlanCalcScoreConfigGroup:416 scoring parameters for subpopulation null were just overwritten.
aido-host_1   | 2019-01-04 22:27:45,155  INFO Config:563 setting context to [file:/amod/target/config.xml]
aido-host_1   | 2019-01-04 22:27:45,155  INFO ScenarioLoaderImpl:108 loading scenario from base directory: /amod/target/
aido-host_1   | 2019-01-04 22:27:45,156  INFO ScenarioLoaderImpl:130 loading network from file:/amod/target/preparedNetwork.xml.gz
aido-host_1   | 2019-01-04 22:27:45,156  INFO MatsimXmlParser:155 starting to parse xml from url file:/amod/target/preparedNetwork.xml.gz ...
aido-host_1   | 2019-01-04 22:27:45,157  INFO MatsimNetworkReader:95 using network_v2-reader.
aido-host_1   | 2019-01-04 22:27:45,158  INFO MatsimXmlParser:306 Using local DTD from classpath:dtd/network_v2.dtd
aido-host_1   | 2019-01-04 22:27:45,159  INFO NetworkImpl:156  node # 1
aido-host_1   | 2019-01-04 22:27:45,160  INFO NetworkImpl:156  node # 2
aido-host_1   | 2019-01-04 22:27:45,160  INFO NetworkImpl:156  node # 4
aido-host_1   | 2019-01-04 22:27:45,161  INFO NetworkImpl:156  node # 8
aido-host_1   | 2019-01-04 22:27:45,161  INFO NetworkImpl:156  node # 16
aido-host_1   | 2019-01-04 22:27:45,162  INFO NetworkImpl:156  node # 32
aido-host_1   | 2019-01-04 22:27:45,163  INFO NetworkImpl:156  node # 64
aido-host_1   | 2019-01-04 22:27:45,165  INFO NetworkImpl:156  node # 128
aido-host_1   | 2019-01-04 22:27:45,168  INFO NetworkImpl:156  node # 256
aido-host_1   | 2019-01-04 22:27:45,171  INFO NetworkImpl:156  node # 512
aido-host_1   | 2019-01-04 22:27:45,174  INFO NetworkImpl:156  node # 1024
aido-host_1   | 2019-01-04 22:27:45,180  INFO NetworkImpl:156  node # 2048
aido-host_1   | 2019-01-04 22:27:45,190  INFO NetworkImpl:156  node # 4096
aido-host_1   | 2019-01-04 22:27:45,208  INFO NetworkImpl:156  node # 8192
aido-host_1   | 2019-01-04 22:27:45,240  INFO NetworkImpl:156  node # 16384
aido-host_1   | 2019-01-04 22:27:45,269  INFO NetworkImpl:152  link # 1
aido-host_1   | 2019-01-04 22:27:45,269  INFO NetworkImpl:152  link # 2
aido-host_1   | 2019-01-04 22:27:45,270  INFO NetworkImpl:152  link # 4
aido-host_1   | 2019-01-04 22:27:45,270  INFO NetworkImpl:152  link # 8
aido-host_1   | 2019-01-04 22:27:45,270  INFO NetworkImpl:152  link # 16
aido-host_1   | 2019-01-04 22:27:45,271  INFO NetworkImpl:152  link # 32
aido-host_1   | 2019-01-04 22:27:45,271  INFO NetworkImpl:152  link # 64
aido-host_1   | 2019-01-04 22:27:45,272  INFO NetworkImpl:152  link # 128
aido-host_1   | 2019-01-04 22:27:45,274  INFO NetworkImpl:152  link # 256
aido-host_1   | 2019-01-04 22:27:45,276  INFO NetworkImpl:152  link # 512
aido-host_1   | 2019-01-04 22:27:45,279  INFO NetworkImpl:152  link # 1024
aido-host_1   | 2019-01-04 22:27:45,287  INFO NetworkImpl:152  link # 2048
aido-host_1   | 2019-01-04 22:27:45,299  INFO NetworkImpl:152  link # 4096
aido-host_1   | 2019-01-04 22:27:45,324  INFO NetworkImpl:152  link # 8192
aido-host_1   | 2019-01-04 22:27:45,372  INFO NetworkImpl:152  link # 16384
aido-host_1   | 2019-01-04 22:27:45,511  INFO NetworkImpl:152  link # 32768
aido-host_1   | 2019-01-04 22:27:45,638  INFO ScenarioLoaderImpl:182 no facilities file set in config, therefore not loading any facilities.  This is not a problem except if you are using facilities
aido-host_1   | 2019-01-04 22:27:45,638  INFO ScenarioLoaderImpl:192 no facility-attributes file set in config, not loading any facility attributes
aido-host_1   | 2019-01-04 22:27:45,638  INFO ScenarioLoaderImpl:199 loading population from file:/amod/target/preparedPopulation.xml.gz
aido-host_1   | 2019-01-04 22:27:45,638  INFO MatsimXmlParser:155 starting to parse xml from url file:/amod/target/preparedPopulation.xml.gz ...
aido-host_1   | 2019-01-04 22:27:45,640  INFO PopulationReader:109 using population_v6-reader.
aido-host_1   | 2019-01-04 22:27:45,640  INFO MatsimXmlParser:306 Using local DTD from classpath:dtd/population_v6.dtd
aido-host_1   | 2019-01-04 22:27:45,642  INFO PopulationImpl:112  person # 1
aido-host_1   | 2019-01-04 22:27:45,643  INFO PopulationImpl:112  person # 2
aido-host_1   | 2019-01-04 22:27:45,643  INFO PopulationImpl:112  person # 4
aido-host_1   | 2019-01-04 22:27:45,643  INFO PopulationImpl:112  person # 8
aido-host_1   | 2019-01-04 22:27:45,644  INFO PopulationImpl:112  person # 16
aido-host_1   | 2019-01-04 22:27:45,644  INFO PopulationImpl:112  person # 32
aido-host_1   | 2019-01-04 22:27:45,645  INFO PopulationImpl:112  person # 64
aido-host_1   | 2019-01-04 22:27:45,647  INFO PopulationImpl:112  person # 128
aido-host_1   | 2019-01-04 22:27:45,649  INFO PopulationImpl:112  person # 256
aido-host_1   | 2019-01-04 22:27:45,652  INFO PopulationUtils:992  person # 500
aido-host_1   | 2019-01-04 22:27:45,652  INFO ScenarioLoaderImpl:235 no person-attributes file set in config, not loading any person attributes
aido-host_1   | 2019-01-04 22:27:45,652  INFO ScenarioLoaderImpl:247 no households file set in config, not loading households
aido-host_1   | 2019-01-04 22:27:45,652  INFO ScenarioLoaderImpl:258 no household-attributes file set in config, not loading any household attributes
aido-host_1   | 2019-01-04 22:27:45,652  INFO ScenarioLoaderImpl:284 no transit schedule file set in config, not loading any transit schedule
aido-host_1   | 2019-01-04 22:27:45,653  INFO ScenarioLoaderImpl:311 no transit vehicles file set in config, not loading any transit vehicles
aido-host_1   | /amod/target/linkSpeedData
aido-host_1   | INFO loading link speed data from file /amod/target/linkSpeedData
aido-host_1   | StringServerSocket: closed
aido-host_1   | com.google.inject.CreationException: Unable to create injector, see the following errors:
aido-host_1   | 
aido-host_1   | 1) Explicit bindings are required and ch.ethz.idsc.amodeus.traveldata.TravelData is not explicitly bound.
aido-host_1   |   while locating ch.ethz.idsc.amodeus.traveldata.TravelData
aido-host_1   |     for field at ch.ethz.idsc.amodeus.matsim.mod.VehicleToVSGenerator$Factory.travelData(VehicleToVSGenerator.java:119)
aido-host_1   |   at ch.ethz.idsc.amodeus.matsim.mod.AmodeusVehicleGeneratorModule.install(AmodeusVehicleGeneratorModule.java:18) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> ch.ethz.idsc.amodeus.matsim.mod.AmodeusVehicleGeneratorModule)
aido-host_1   | 
aido-host_1   | 2) Explicit bindings are required and ch.ethz.idsc.amodeus.virtualnetwork.VirtualNetwork<org.matsim.api.core.v01.network.Link> is not explicitly bound.
aido-host_1   |   while locating ch.ethz.idsc.amodeus.virtualnetwork.VirtualNetwork<org.matsim.api.core.v01.network.Link>
aido-host_1   |     for field at ch.ethz.idsc.amodeus.matsim.mod.VehicleToVSGenerator$Factory.virtualNetwork(VehicleToVSGenerator.java:119)
aido-host_1   |   at ch.ethz.idsc.amodeus.matsim.mod.AmodeusVehicleGeneratorModule.install(AmodeusVehicleGeneratorModule.java:18) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> ch.ethz.idsc.amodeus.matsim.mod.AmodeusVehicleGeneratorModule)
aido-host_1   | 
aido-host_1   | 2 errors
aido-host_1   | 	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
aido-host_1   | 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
aido-host_1   | 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
aido-host_1   | 	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232)
aido-host_1   | 	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:236)
aido-host_1   | 	at org.matsim.core.controler.Injector.createInjector(Injector.java:73)
aido-host_1   | 	at org.matsim.core.controler.Controler.run(Controler.java:189)
aido-host_1   | 	at amod.aido.AidoServer.simulate(AidoServer.java:134)
aido-host_1   | 	at amod.aido.AidoHost.main(AidoHost.java:116)
aido-host_1   | Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:
aido-host_1   | 
aido-host_1   | 1) Explicit bindings are required and ch.ethz.idsc.amodeus.traveldata.TravelData is not explicitly bound.
aido-host_1   |   while locating ch.ethz.idsc.amodeus.traveldata.TravelData
aido-host_1   |     for field at ch.ethz.idsc.amodeus.matsim.mod.VehicleToVSGenerator$Factory.travelData(VehicleToVSGenerator.java:119)
aido-host_1   |   at ch.ethz.idsc.amodeus.matsim.mod.AmodeusVehicleGeneratorModule.install(AmodeusVehicleGeneratorModule.java:18) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> ch.ethz.idsc.amodeus.matsim.mod.AmodeusVehicleGeneratorModule)
aido-host_1   | 
aido-host_1   | 2) Explicit bindings are required and ch.ethz.idsc.amodeus.virtualnetwork.VirtualNetwork<org.matsim.api.core.v01.network.Link> is not explicitly bound.
aido-host_1   |   while locating ch.ethz.idsc.amodeus.virtualnetwork.VirtualNetwork<org.matsim.api.core.v01.network.Link>
aido-host_1   |     for field at ch.ethz.idsc.amodeus.matsim.mod.VehicleToVSGenerator$Factory.virtualNetwork(VehicleToVSGenerator.java:119)
aido-host_1   |   at ch.ethz.idsc.amodeus.matsim.mod.AmodeusVehicleGeneratorModule.install(AmodeusVehicleGeneratorModule.java:18) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> ch.ethz.idsc.amodeus.matsim.mod.AmodeusVehicleGeneratorModule)
aido-host_1   | 
aido-host_1   | 2 errors
aido-host_1   | 	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
aido-host_1   | 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
aido-host_1   | 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
aido-host_1   | 	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232)
aido-host_1   | 	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:236)
aido-host_1   | 	at org.matsim.core.controler.Injector.createInjector(Injector.java:73)
aido-host_1   | 	at org.matsim.core.controler.Controler.run(Controler.java:189)
aido-host_1   | 	at amod.aido.AidoServer.simulate(AidoServer.java:134)
aido-host_1   | 	at amod.aido.AidoHost.main(AidoHost.java:116)

**Comment by yoooyle** [comment]
you can reproduce this error by running 
`mvn test`

```
Results :

Tests in error: 
  testSanFrancisco(amod.aido.demo.AidoStarterHelperTest)

Tests run: 16, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:29 min
[INFO] Finished at: 2019-01-04T15:43:50-08:00
[INFO] ------------------------------------------------------------------------
```
[surefire-reports.zip](https://github.com/idsc-frazzoli/amod/files/2728902/surefire-reports.zip)
