### ISSUE TITLE
Geo lab library error: org.opengis.referencing.datum.DatumFactory is not an ImageIO SPI class

### ISSUE THREAD

**Issue by arshdefoamed** [idsc-frazzoli/amod#132]
I downloaded the master version of AMOD, performed Maven Install and tried to run ScenarioPreparer.java. The system gives following error:

Exception in thread "main" java.lang.ExceptionInInitializerError
	at amod.demo.ext.UserLocationSpecs.<clinit>(UserLocationSpecs.java:11)
	at amod.demo.ext.Static.setup(Static.java:13)
	at amod.demo.ScenarioServer.simulate(ScenarioServer.java:65)
	at amod.demo.ScenarioServer.main(ScenarioServer.java:57)
Caused by: java.lang.IllegalArgumentException: org.opengis.referencing.datum.DatumFactory is not an ImageIO SPI class
	at java.desktop/javax.imageio.spi.ServiceRegistry.checkClassAllowed(ServiceRegistry.java:722)
	at java.desktop/javax.imageio.spi.ServiceRegistry.<init>(ServiceRegistry.java:117)
	at org.geotools.factory.FactoryRegistry.<init>(FactoryRegistry.java:155)
	at org.geotools.factory.FactoryRegistry.<init>(FactoryRegistry.java:146)
	at org.geotools.factory.FactoryCreator.<init>(FactoryCreator.java:82)
	at org.geotools.referencing.ReferencingFactoryFinder.getServiceRegistry(ReferencingFactoryFinder.java:115)
	at org.geotools.referencing.ReferencingFactoryFinder.getFactory(ReferencingFactoryFinder.java:197)
	at org.geotools.referencing.ReferencingFactoryFinder.getCRSFactory(ReferencingFactoryFinder.java:288)
	at org.geotools.referencing.CRS.parseWKT(CRS.java:535)
	at org.matsim.core.utils.geometry.geotools.MGC.getCRS(MGC.java:172)
	at org.matsim.core.utils.geometry.transformations.GeotoolsTransformation.<init>(GeotoolsTransformation.java:57)
	at amod.demo.ext.UserReferenceFrames.<clinit>(UserReferenceFrames.java:12)
	... 4 more

As per my research, this error is the result of incompatibility of geotools jar file used by matsim and JDK 8. 
Can someone suggest what should I do to get rid of this issue?

**Comment by claudioglasses** [comment]
Hi Arshdeep, this comes from the fact that we use opengis for coordinate transformations. Unfortunately this library is essential for us but hast not been made compatible to JAVA versions higher than java 8. This error  happens when you try to use amodeus with a JAVA version higher than 8. My suggestion is to use a a JAVA 8 compiler to avoid the error. We regularly check for updated libraries and try to solve the issue. Please feel free to contact me anytime for additional help. My email is: clruch@idsc.mavt.ethz.ch

**Comment by arshdefoamed** [comment]
Thank you so much for your prompt reply. I am already using java 1.8 and I tried to manually compile AMODEUS library and add it as the dependency as well. However, the issue seems to be coming from MATSIM which is downloading geotools 14.0 which is compatible with JAVA 7. Please refer to the following link for the geo tools version details http://docs.geotools.org/latest/developer/conventions/version.html

I have also attached the dependency hierarchy of AMODEUS. Request you to suggest how to handle this.
![Screenshot from 2019-04-23 15-18-46](https://user-images.githubusercontent.com/4056835/56613243-da867980-65db-11e9-821a-63348fc5d687.png)
