### ISSUE TITLE
Running scenarioServer file gives LinkSpeedDataContainer class incompatibility error

### ISSUE THREAD

**Issue by arshdefoamed** [idsc-frazzoli/amod#134]
Hi,
I downloaded AMOD, ran scenarioPreparer on SanFransico data and then ran scenarioServer. Its giving me following error:

`Exception in thread "main" java.io.InvalidClassException: ch.ethz.idsc.amodeus.linkspeed.LinkSpeedDataContainer; local class incompatible: stream classdesc serialVersionUID = 4966479030061221834, local class serialVersionUID = 4797404069347600867
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1885)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2042)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at ch.ethz.idsc.tensor.io.Serialization.parse(Serialization.java:48)
	at ch.ethz.idsc.tensor.io.ObjectFormat.parse(ObjectFormat.java:37)
	at ch.ethz.idsc.tensor.io.Import.object(Import.java:60)
	at ch.ethz.idsc.amodeus.linkspeed.LinkSpeedUtils.loadLinkSpeedData(LinkSpeedUtils.java:24)
	at amod.demo.ScenarioServer.simulate(ScenarioServer.java:108)
	at amod.demo.ScenarioServer.main(ScenarioServer.java:57)`

Can someone suggest how to handle this?

**Comment by claudioglasses** [comment]
The error was resolved, plese pull master.
